
PROJECT_HOME=/usr/local/blacows
KJXUTIL_HOME=$PROJECT_HOME/kjxutil
KJXTAG_HOME=$PROJECT_HOME/kjxtag

LIB_DIR=$KJXTAG_HOME/lib
SCRIPT_DIR=$KJXTAG_HOME/script
SPEC_DIR=$KJXTAG_HOME/spec

RUBY_CMD="ruby -I $LIB_DIR"
